Semantic-Org/Semantic-UI

gulpfile.js
Ensures consistent URLs such as  `url("../themes/default/assets/fonts/icons.eot");` instead of `url("..\themes/default/assets/fonts/icons.eot");`
=> Fix relative paths on windows

src/definitions/modules/dropdown.js
This fix restores the input class "default" as well as removing the
selected item from the list in case the default value is empty (used as
placeholder).
Issue: http://jsfiddle.net/mktm/tmadsvb6/
=> Dropdown module (restore)

src/definitions/behaviors/form.js
Implementing a reset functionality to form module
I implemented this instead of using form native due to Semantic modules, such as checkbox and dropdown (select), plus to avoid having to do "return false" on submitting the form via Ajax.
As instance of module occurs, it will set a data value (defaultValue) to all field identifiers passed through.
As reset is called, it will look these fields and set their value to their respective defaults.
May need a bit more polishing, but works as expected.
Manual call: $('.ui.form').form('reset');
Working example: http://jsfiddle.net/mktm/y5zopezh/
=> Form Reset + Serialize

src/themes/default/elements/icon.overrides
Whew, this took a while. :stuck_out_tongue_closed_eyes: Let me know if you need any changes, or if there's another part of the codebase I need to update in addition to this.
Closes #1642 
Notes:
* The Font Awesome attribution/license banner was shortened here: https://github.com/FortAwesome/Font-Awesome/commit/6fbbefc89fa530c55a33bb5277d8b56ef27b3015
* `signal` and `wifi` are now two separate icons
* Added the `Gender` and `Payment Options` categories
* The `i.icon.plane` was repeated so I removed the second entry
* Font Awesome reference can be found [here](http://fontawesome.io/cheatsheet/) and [here](http://fontawesome.io/icons/)
=> Update icons to support Font Awesome 4.3

README.md
http://cl.ly/image/0Z461V1s371S
http://cl.ly/image/2b0m2T1F3y1X
etc...
I think it is misleading to list IE 9 under browser support.
=> Correct IE9 support status

src/definitions/modules/popup.js
In an Angular JS application of mine I was suffering from a terrible memory leak. The extensive use of Semantic UI popups made me think they are the culprit. So I investigated a bit and found the cause. The **initialize** method of the Popup module attaches a listener on the **window.resize** event.but does not unbind it when its **destroy** behaviour is invoked. The proposed changes solve the memory leak.
=> [Popup] Doesn't remove Window Events on Destroy

src/definitions/elements/image.less
Currently, images which have height and width attributes set in the HTML don't resize correctly with the size and fluid classes (`ui small image`, `ui fluid image`, etc.). Those attributes are frequently used to avoid the content jumping around in case images take some time to load, which is why I figured this simple fix might be useful.
What happens in the actual version: the images get squeezed horizontally but not vertically, not preserving their aspect ratio.
What happens after my changes: the image gets resized both horizontally and vertically, keeping their aspect ratio intact.
=> Fix image deformation when using fluid or size classes

src/definitions/modules/progress.less
"@progressPosition" is declared in the default theme but not used in the definition file, making it impossible to override.
=> Fixed declared but unused variable

src/definitions/collections/form.less
The required field style shouldn't apply to fields nested within grouped fields - #1988
=> Moving required field indicator on grouped fields to group label

src/definitions/collections/form.less
When you use an inline field, select should also be `inline` the same as input
Demonstrate at http://jsfiddle.net/tey5po7t/1
=> Fix <select> inside form inline field

README.md, package.json, tasks/config/docs.js, tasks/docs/build.js, tasks/docs/metadata.js
1. Adds a new task `metadata.js` that parses a docpad *.html.eco template and extracts the metadata from the beginning of the file.
2. Accumulates metadata into a `JsonArray`, each element containing a `JsonObject` that describes the file from 1.
3. Emits a new file into sister directory, typically `../docs/out/src/metadata.json`.
Rebased onto next that pulled in change from another user.  Sorry.
=> Scrape yaml metadata from docs repo and generate metadata.json

src/definitions/modules/accordion.js
I added a new callback to the Accordion module, named `onOpening`, which will be triggered before the Accordion menu is about to be opened.
=> Add onOpening callback to Accordion

src/definitions/modules/progress.js
I was attempting to put decimals in the progress bar (e.g. 9.4 of 10) and found that the precision rounding order of operations was out of order causing everything to round to 0 decimals. 
I corrected that order, however, many people may have gotten used to this behavior so the only additional change I considered was defaulting the precision to 0. 
I hope this helps!
=> Corrected order of operations to enable precision (rounding).

package.json
Please use https/tarball for wrench dependancy instead of git protocol, as it is more portable and doesn't require git to be installed.
=> "wrench" depencency as tarball

src/definitions/elements/list.less, src/themes/default/elements/list.variables
See http://jsfiddle.net/ka98j2pv/2/
This commit introduces @orderedInvertedCountColor for this purpose.
@jlukic If prefer to make changes on your branch and close this PR, no biggie.
=> Make ordered list numbers in an inverted context be visible

bower.json
Per bower/bower.json-spec#43 :
> Use source files with module exports and imports over pre-built distribution files.
Also, the example in that PR includes `/sass/motion.scss` in and excludes `/dist/movement.css` & `/dist/movement.min.css` from its `main`.
=> bower.json: main: semantic.css => semantic.less

src/definitions/elements/icon.less
The issue is pretty much the same as #662, but now in webkit. Using -webkit-font-smoothing: antialiased solves the problem.
I made a jsfiddle that demonstrate it: http://jsfiddle.net/davialexandre/trx0bpz8/. Here is an image of how the icons are rendered (I am using a dark background to make it easier to notice the difference). The first row is using -webkit-font-smoothing and the second one is how the icons are currently rendered:
=> Fixes icon rendering problem in OSX + webkit

src/definitions/globals/site.less, src/themes/default/globals/site.variables, src/themes/flat/globals/site.variables, src/themes/material/globals/site.variables
I'm working on a site where I need links to be underlined when hovered, but otherwise not.
This patch allows you to add @linkHoverUnderline to your site.variables to make this possible.
=> Allow link underline and hover link underline to differ

src/definitions/modules/transition.js
This error was being triggered in Firefox.
=> Fixes "SyntaxError: unreachable code after return statement"

src/definitions/modules/popup.js
As suggested in `popup parent position ~absolute/fixed will not display` #2518
removing the popup position check..
=> remove popup position check

src/definitions/modules/dropdown.js
This problem happens only when we have a dropdown created from a select
that loads remote content. In this scenario, we don't know in advance
which choices will be available, so we start with a select without any
options. When an choice is selected, module.set.value will try to set
the select value, but it will fail, since there's no options.
To fix this, module.set.value will add a new option to the select, before
setting the value. This will be done only if the dropdown input is a select
and if we are dealing with remote loaded content.
=> Properly set the dropdown value when dealing with remote loaded choices

tasks/README.md
There appeared to be a spacing error for line 13 and an extra paren on line 14.
=> Fixed typo in README.md

tasks/build.js, tasks/watch.js
See Semantic-Org/Semantic-UI#2653
=> fix build/watch for people importing tasks into their own gulpfile

dist/components/flag.css
Hi, my first (and tiny) pull request here. Thanks for the great work on Semantic-UI. Issue #1549 removed the alias uk-england but england itself was never added back.
=> [Flag] Add England Alias

src/definitions/modules/popup.js
Specifying inline:true to popups should find .ui.popup in all siblings, not just the immediately following one (sometimes it isn't possible to guarantee that the popup is written immediately next, esp. with ajax content and complex sites).
=> [Popup] Look for inline popup in all siblings of target, not just immediate sibling

tasks/admin/components/create.js
Fixes npm packaging for components api, site (#1878) and transition.
This patch is re-implementation of fixes done in pull request 1156 (https://github.com/Semantic-Org/Semantic-UI/pull/1156) following some concerns raised in #1878.
=> Update RegExps in packaging for npm.

dist/components/api.js
I just read your [documentation](http://semantic-ui.com/behaviors/api.html#/settings) and you say that the debug option is false by default but it doesn't, it was true. I just changed this to false so it fits with your documentation.
Regards!
=> Set API.settings.debug to false as documented

src/definitions/modules/sticky.js
For fluid menus (constrained in width by a grid of some description), the sticky needs to update the dimensions with !important, since it needs to override:
.ui.menu.fluid,.ui.vertical.menu.fluid{
width:100%!important
}
Otherwise, the sticky menu will simply flow all over the screen..
=> Sticky position fix for fluid menus

src/definitions/modules/dropdown.js
I found out that there is no way to prevent dropdown from being hidden in specific cases, so I thought this might be quite handy.
In my scenario, I use an input field with attached `jquery-datepicker` and whenever I want to jump between month in it, the dropdown hides.
Therefore I propose to add this small feature.
=> [Dropdown] Allow `onHide` callbacks to prevent Hiding

CONTRIBUTING.md, README.md
I've noticed you have to tag a lot of issues with "Read the Contributing Guide / Readme" or "Should Use StackOverflow / Gitter".
This PR adds a badge and links to the Semantic-UI message board on ProjectTalk and hopefully redirects these questions there.
I only recently started ProjectTalk. If you consider this PR Spam, please excuse and let me know. But I think it's genuinely useful.
I also noticed you already use google groups, but I think ProjectTalk has a number of benefits over that. For one, having the badge in your Readme, it's just more visible. Also, people won't need a google account. And most importantly, it's just more beautiful, as it's built with Semantic-UI ;-)
=> add projecttalk to readme

src/definitions/elements/step.less
There's an issue with the single step element where the border radius style is adhering to a "last child" case. You can see the bug here: http://jsfiddle.net/o7wn9xjd/. I am able to replicate in IE10, IE11, Chrome, Safari and Firefox (I did not test the mobile browsers).
The solution addresses the concept of "the latter rule wins". In this case, the rule for `:last-child` holds true during any `:only-child` case. This was overriding the `:only-child` style.
=> Single step border radius fix

src/definitions/modules/nag.js
Fixed an issue in Nag module > storage.remove which was checking settings.storageMethod with an incorrect value and was also checking window for a store property which does not exist.
Added support for sessionstorage to Nag module to enable nags to be shown once per session.
=> [Nag] Fix issue with localstorage and add support for session storage

src/definitions/modules/embed.js
Equals after the question mark caused parameters not to be recognised by youtube.
=> Fixed bad template url

src/definitions/modules/dropdown.js
ref: #2981 
Just add disabled state if the origin is disabled.
```html
<select class="ui dropdown" disabled>
</select>
```
to
```html
<div class="ui dropdown selection disabled">
</div>
```
test: https://jsbin.com/rapopus/edit?html,output
=> [dropdown] Preserve initial disabled state

src/definitions/elements/divider.less, src/definitions/elements/step.less, src/definitions/modules/modal.less, src/definitions/views/ad.less
In `modal.less` and `step.less`, a `max-width` of `@computerBreakpoint` is used, causing an inconsistency when the browser is exactly 992px width (ie most queries switch on the 991-992 change, but these switch on the 992-993 change).
- `@largest*` should only be used by `max-width` queries
- `@*Breakpoint` should only be used by `min-width` queries
This PR makes the use of these variables more consistent.
=> Fixed inconsistent use of media query breakpoints

src/definitions/modules/modal.js
Currently the modal allows the user to cancel a hide from the `onDeny` and `onApprove` callbacks, but not from the `onHide`. This could be useful if you want to stop the user from hiding a modal but don't want to set `closable` to false.
For example, if you have a popup that submits a request to the server, and you want to display a loading state after the user has submitted, you could temporarily disable closing the popup by returning false from the `onHide` callback while the form submission is in progress.
Happy to also create a PR for the docs repository documenting this change.
=> Ability to cancel a modal hide from the onHide callback

src/definitions/collections/grid.less
The grid `row`/`column` classes use the `widescreen only` selector, however in the parent `grid` class only `widescreen` is present (missing `only`). Also, in the mobile only hide, the `row`/`column` `widescreen only` is missing, with `large screen only` repeated twice (probably simply a forgotten find/replace after a copy/paste).
Additionally switches the tablet only class selector on the mobile only hide from `.tablet:not(.mobile).only` to `[class*="tablet only"]:not(.mobile)`, for consistency with the surrounding selectors.
=> Inconsistency with `widescreen only` class

src/definitions/modules/dimmer.js
If the dimmer has a opacity setting of 0, the CSS background-color is set to `rgba(0, 0, 0, undefined)`, due to the way the opacity variable is set. This PR accounts for an opacity setting of 0.
=> Support for dimmer with zero opacity

tasks/build/css.js
fix build-css task callback timing
=> callback on correct timing

src/definitions/elements/flag.less
Fix for #3260. When a flag has a missing or invalid country class name, render blank instead of showing the flag of Andorra.
=> Fix for flags with invalid country class

tasks/config/project/install.js, tasks/install.js
This feature is added to allow to automatize a semantic-ui
re-installation with the same configuration (such as in your CI build)
To switch it on, simply add ("auto-install": true) in semantic.json
Of course, configuration name could be changed :)
=> Add an automatic reinstallation process based on semantic.json

src/definitions/modules/dimmer.js
During the second dimmer run the color was extracted from the DOM. At
least Firefox automatically converts RGBA to RGB if possible which
caused the bug.
With this fix the dimmer module can now detect both RGB and RGBA colors.
=> fix modal/dimmer inverted bug #3192

src/definitions/modules/nag.js
https://github.com/Semantic-Org/Semantic-UI/issues/211#issuecomment-106290794
As mentioned above the nag module is missing the easing function to work properly. The normal jquery library only supports 'swing' and 'linear' easing functions. The added code is a copy from here: 
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/accordion.js#L589-L593
Please merge and make people happy :tada:
=> Bake 'easeOutQuad' easing function into nag module.

README.md
Fields are using `pointer-events: none` when disabled with `<div class="disabled field">...</div>`, thus avoiding the children to be clicked. However, this CSS property isn't supported by Internet Explorer 10, [according to CanIUse](http://caniuse.com/#feat=pointer-events).
=> Set Internet Explorer support to 11+

src/definitions/behaviors/form.js
In the end I did a bit of research and borrowed the [email regex used in angular.js](https://github.com/angular/angular.js/blob/4487d4a8a477ad440500e3574c141da48d13ab3d/src/ng/directive/input.js#L27).
=> Email fix for #3755

README.md
On NPM the projectTalk button link looks like this:
This was caused by an extra line break in the markdown. Github seems to compensate for this automatically, while npm does not.
=> Correct ProjectTalk Button link in Readme on NPM

package.json
It allows some tools like `npm-css` and `postcss` to import styles from the node_modules directory. It's awesome to write just `@import "semantic-ui"` to load css.
=> Add a style option

src/definitions/collections/form.less
Add inline-block to compact form messages so they don't take the full width of their container.
Fixes #3343
=> Fix compact form messages

src/definitions/collections/menu.less
Removed duplicate height definition to respect the `@dividerSize` variable
=> [Menu] @dividerSize cannot be changed since it is hard coded

src/definitions/modules/dropdown.js
Dropdown function 'disconnect.selectObserver' trying to disconnect menuObserver instead. #4311
=> [Dropdown] Disconnect.selectObserver bugfix

src/themes/default/elements/icon.overrides
` i.icon.talk:before { content: "\f27a"; }` was re-declared in "Aliases" section with different content value `"\f075"`.
The alias was overriding the correctly declared talk icon.
You can look in the docs http://semantic-ui.com/elements/icon.html, the "Talk" icon should be same as "Talk Outline" (with just the outline of course).
=> [Icons] Removed duplicated 'talk' icon with incorrect content

src/definitions/collections/form.less
in form validation, type="file" is working properly but the style
doesn't change properly. Because there are missing points. I add css
selectors for input[type="file"] in this file so that we can see some
'error' style for input[type="file"].
=> [Input] ADD the same style for input[type="file"].

src/themes/material/collections/menu.overrides, src/themes/material/elements/button.overrides, src/themes/material/elements/header.overrides, src/themes/material/modules/dropdown.overrides, src/themes/material/modules/modal.overrides
The default material theme uses http:// for the fonts in every override file, which throws warnings on SSL enabled sites. This fixes that.
=> Update material theme font URLs to be '//' instead of 'http://'

src/themes/flat/collections/form.variables
This is an attempted fix for #1802, which was closed as a `Cannot fix`.
On the current website, with the Flat theme selected.
=> Fix fg-color on inverted forms in flat theme.

tasks/install.js
With 'autoInstall: true' in semantic.json, npm install does not copy out the semantic files to root directory. 
The following check always fails when install.shouldAutoInstall() === true
``` javascript
/*--------------
NPM Install
---------------*/
// Check if PM install
if(answers.useRoot || answers.customRoot) {
```
=> FIX: auto install did not copy build during npm install

src/definitions/modules/dropdown.js
Dropdown local search only happened with local data, and dropdown with remote api will search the data by continuous invoking API with query parameter. 
Since for some scenarios, we just want to retrieve the data once from the server, and search the data locally. To support this requirement, I have enhanced the dropdown module to support local search when data is retrieved from remote API.
`localSearch` is default to `false`, so it will not effect the existing features of dropdown widget. If the user needs to enable local search with remote API data, then simply set the `localSearch` setting to `true` as follow:
```
$modelDropdown.dropdown({
apiSettings: {
url: '/api/data.json'
},
fields: {
name  : 'name', // displayed dropdown    
value : 'id'         // actual dropdown value
}, …
```
=> [Dropdown] Add "localsearch" Setting to allow local search when dropdown data retrieved from remote API

src/definitions/modules/slider.js, src/definitions/modules/slider.less
There are following changes:
- Code cleaning and format;
- Add slider container padding when locating labels;
- Use css function `calc()` to locate thumb, track fill and labels, so no need to listen resize event or observe element changes;
- Extra parameter `thumbVal`, `secondThumbVal` for listener `onChange()` and `onMove()`;
- Exactly updating global variables `value`, `module.thumbVal`, `module.secondThumbVal`, `position` and `secondPos`;
- Set or update `value` to `min` or `max` when mouse is moving out slider;
=> Slider: bugfix and improving implements

src/definitions/elements/icon.less
Related to requests from issue #904 , added position classes for corner icons (top right, top left, bottom right, bottom left)
=> Added 4 positions for corner icons

src/definitions/modules/modal.less, src/themes/default/modules/modal.variables
It seems to be a common request: #3214. Feel free to modify the variables; I’ve been using these settings for quite a while, and considering the optimal line length of the default theme’s font size, `0.4` ratio works great with small forms, messages or text. Not so sure about `@tinyHeaderSize` that I kept at `1.3em`, though.
I’ll submit a PR to the documentation as soon as I figure out how to add JavaScript to it.
=> Added a `.tiny` modal size

src/definitions/modules/modal.js
This commit solves #4196
When two or more modals coexist on the same page, the refresh method
of each modal is executed, even if one of them is being shown.
By checking if the module is active or being animated, you prevent
conflicts between shown and hidden modals, like the one described in
the issue.
=> [Modal] #4196 Disable refreshing for non active/animated modals

CONTRIBUTING.md, README.md
Resolves #5521. I also updated jQuery and attached it to my account to be able to change the JSFiddle without the need to update the markdown files. Ideally, I think, SUI should have its own JSFiddle account.
=> [Docs] #5521 Update the JSFiddle to use HTTPS

src/definitions/elements/step.less
Fix for #3439.
Now, when using .step, you may provide .unstackable (unresponsive) class to disable stacking of Step element.
=> Fix #3439 - Now steps can be .unstackable

src/definitions/modules/popup.js
The code was comparing the result of `typeof` with a variable named `undefined`.
As typeof returns a string it should compare to `'undefined'`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/semantic-org/semantic-ui/4544)
=> Correct check for undefined variable

src/theme.config.example, src/theme.less
This an enhancement for making the default theme folder configurable. In the following, I describe a use case which motivates this pull request.
We use Semantic-UI at VANTAiO for styling our portal solutions. We provide a common Semantic theme which can be adjusted for each customer.
We implemented this by creating a copy of the default Semantic theme and naming it "common". We adjusted variables in the .variables files and extended the css in the .overrides files. When we need to customize a theme for a customer, we copy this common theme. All adjustments are performed in this theme.
This appproach leads to problems. When we want to perform changes in the common theme, we have to manually adjust the customized theme files. Furthermore, there is lots of redundant code. Differences between …
=> [Build Tools] Default theme folder can be configured

src/definitions/elements/button.less
Because the starting style for color includes `!important`, it always wins out against any value you set for `@basicActiveTextColor`.
https://github.com/Semantic-Org/Semantic-UI/blob/796d2f66e26ae5bb76c604fe6a36914ad3d2fe2a/src/definitions/elements/button.less#L705-L708
This PR just adds `!important`, which then makes it win because now the two compete with a level playing field and `.ui.basic.active.button` is higher than `.ui.basic.button`.
***
It's not clear why `!important` is used in semantic, but I imagine it has a legitimate reason and the topic discussed ad nauseam, so I think this is likely the desired solution with the status quo.
=> [Buttons] fix for active basic button text color always having a lower specificity due to !important

src/definitions/modules/dropdown.less
=> [Dropdown] The width of inputs that are inside of a dropdown’s `.menu` should never be overridden

tasks/admin/components/init.js
This PR fixes a simple typo with significant consequences.
The missing colon at the end of line 68 causes implicit semicolon
insertion to happen, this ends the variable declaration statement that
starts on line 67. The nine assignments on the 69-79 then becomes
assignments to global variables.
I found this error with automatic analysis of your project:
https://lgtm.com/projects/g/Semantic-Org/Semantic-UI/snapshot/afe18811db795be24bdb23ca99b22ac2fa948aad/files/tasks/admin/components/init.js?sort=name&dir=ASC&mode=heatmap&excluded=false
You can see more (less serious) errors here: https://lgtm.com/projects/g/Semantic-Org/Semantic-UI/alerts
(full disclosure: I work for lgtm.com)
=> Add missing comma: makes 9 global vars local

src/themes/default/modules/popup.variables
To customize Popup color you have to explicitly set both `@background` and `@arrowBackground` variables.
In most cases arrow color should match popup background color.
=> [Popup] Use @background value for arrow background color

src/themes/default/collections/menu.variables
Issue #5899 
Closes #5899
Changed menu variables to be _big -> huge -> massive_ to be consistent with global variables.
=> Swap huge and big in menu.variables #5899

src/definitions/modules/popup.js
Since settings starts off as false, if it was passed in, it should be taken before title is returned. Workflow should still stay the same, since settings.content false would still default to title.
=> Take content settings before attr title

src/definitions/behaviors/form.js
https://github.com/Semantic-Org/Semantic-UI/issues/4422
=> 'on: change' causes error prompts to appear when blurring field 

src/definitions/behaviors/form.js
Reverts Semantic-Org/Semantic-UI#4423
=> Revert "'on: change' causes error prompts to appear when blurring field "

src/definitions/modules/dimmer.less
The definition references the wrong variable: `@textColor` instead of `@invertedTextColor` which is defined in https://github.com/Semantic-Org/Semantic-UI/blob/ebb1cab098cad4509d8b173bd1d185b7472711f6/src/themes/default/modules/dimmer.variables#L54.
=> Fix inverted dimmer text color

src/definitions/elements/input.less
A fix for my own issue #4057 which pertained to having a multiple select dropdown inside a popup that was attached to an icon input.
The fix is that an icon input applies padding-right: @iconMargin !important; to all input children of an icon input. This caused problems with the inputs inside the popup which also received this padding. This also caused the search input text to disappear in the multiple select within the popup.
=> [Icon Input] Fix for issue #4057

dist/semantic.js
There are callbacks that happen before open and close, so why not change as well?
Well this fixes that!
I added it so that I have a folder icon on the accordion, so I could just add
`onChanging: function() { $('#file_icon').toggleClass("open"); }`
to initialization to make it change the icon to be open or closed before the animation happened, as opposed to after the animation
=> Added onChanging callback to accordion

.github/stale.yml
This PR adds the config for [stalebot](https://github.com/probot/stale).  This was agreed in the [recent conversation](https://github.com/Semantic-Org/Semantic-UI/issues/6109#issuecomment-366872453) about how to help move things forward.
I've set issues to be marked stale at 90 days of no activity and closed if no activity persists for 30 more days.
We've been using stalebot with this config over at SUIR for a while and it is going well.
=> Setup stalebot for stale issue management

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, src/definitions/modules/search.js
#6221 
Avoid possible duplicate results when `fullTextSearch` is set to `exact`.
=> Fix #3486: [Search] add exactResults on duplicate check

src/definitions/collections/menu.less
#6147
Previously, a disabled item in a ui.menu.secondary would still change state when hovered over.
This PR makes the relevant tags important, preventing this from happening
[Before](https://jsfiddle.net/awei01/xho6Lxv9/)
[Fixed](https://jsfiddle.net/tcmal/j4vh2o48/4/)
=> [Menu] Disabled menu items still changing state on hover

src/definitions/elements/label.less
Fixes  #4476
As noted in the issue, currently, all `.ui.basic.labels` use a solid white background.  This prevents there usage on any other color background.
The proposed fix was to use a transparent background.  However, there is already a variable for basic background color.  I've simply used that variable in all of the basic rules, rather than only in the default basic rule.
=> [Label] Use basicBackground in all basic rules

src/README.md
[src/readme.md] Fixed formatting and bash comments.
=> Fixed some formatting

RELEASE-NOTES.md, src/definitions/modules/dimmer.js, src/definitions/modules/dimmer.less, src/definitions/modules/modal.js, src/definitions/modules/modal.less
Fixes #6185 #6267 #6272 and addresses the comment from `2.3.3`
Modal and dimmer are now implemented with a setting `useFlex` which either defaults to `auto` (modal) or `true` dimmer. 
Fixes support for
* `detachable: false` modals not positioning correctly
* Multiple modals when `allowMultiple: true` not working with `flex` positioning
=> Legacy modals

src/theme.less
allow "null" values for @site theme config variable, like all other variables already allow.
as the default theme is always imported, using "null" values for all variables decreases dramatically the bundle size by avoiding duplicates when using default theme. this improvement is noticeable even when using optimizers like cssnano.
ps: i am calling "null" values that cause the optional import not to find any file.
=> [Theme]: allow null @site

tasks/config/admin/templates/css-package.js
Trying add the semantic-ui package to a meteor project raise the next error:
```
$ meteor add semantic:ui-css
=> Errors while adding packages:             
While building package semantic:ui-css:
error: No plugin known to handle file 'themes/default/assets/fonts/icons.eot'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('themes/default/assets/fonts/icons.eot', 'client').
error: No plugin known to handle file 'themes/default/assets/fonts/icons.svg'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('themes/default/assets/fonts/icons.svg', 'client').
error: No plugin known to handle file 'themes/default/assets/fonts/icons.ttf'. If you want this file to be a static asset, use addAssets instead of …
```
=> [Build Tools] Meteor package: Use `api.addAssets` for static files

tasks/config/admin/templates/composer.json
Invalid `composer.json` file caused issues when installing Semantic UI in my theme folder in a Sylius project. It searches for `composer.json` files and validates them. Because it was invalid Sylius/Symfony would throw a configuration error.
Go into `tasks/config/admin/templates` and run `composer validate`
You will see:
Apply fix and run `composer validate`
=> [Build Tools] Fix invalid composer.json file.

src/definitions/elements/icon.less
See my initial issue https://github.com/Semantic-Org/Semantic-UI-React/issues/4088 
I moved `icon-loading` animation into `:before` element itself.
**Before**: https://jsfiddle.net/afkm1v7w/
**After**: https://jsfiddle.net/t16y3wLk/
(I demonstrated my changes in temporary CSS override)
=> [Icon] Fixed background issue when Icon is used as Labeled Icon for Button as loading one
