src/definitions/behaviors/form.js
form.get.values: Treatment for name[] identifiers while getting the
values
With this you can use form('get values') and inputs with name attribute that is an array return the array of values set.
=> Treatment for name[] identifier

tasks/config/admin/templates/css-package.js
Fixed https://github.com/Semantic-Org/Semantic-UI-CSS/issues/2
=> Removed duplicate line

src/definitions/behaviors/api.js
Resolves #2071
@jlukic Let me know what you think!
=> Implement filter function for transforming server responses

src/definitions/modules/checkbox.js
The this in the call to refresh() from MutationObserver is the module itself not the DOM jquery object. Changing to element fixed it.
=> The wrong this

src/definitions/views/statistic.less
#2280 Implement missing inverted olive statistic.
=> #2280 Update statistic.less

CONTRIBUTING.md
Added CONTRIBUTING.md for `next` branch with updated jsFiddle URL.
=> CONTRIBUTING.md for `next`

src/definitions/modules/dropdown.js
Hi, as for the pr #2308 there is a problem with the data cached values in the dropdown.
I didn't create a jsfiddle cause is the same bug of the other time, but this time in the dropdown.
Hope my contribution will be appreciated.
=> Dropdown data cache

tasks/config/tasks.js
Updated browser prefix config: changed version to versions
=> Updated browser prefix config

src/definitions/collections/menu.less, src/themes/default/collections/menu.variables
The variable @tabularBackgroundColor was referenced in menu.variables but not actually used in menu.less
=> Add missing background-color variable for tabular menu

src/definitions/collections/form.less
@inputWidth exists in form variables file but is not actually used by form.less
=> add missing @inputWidth var to form.less

tasks/build.js
Reverts Semantic-Org/Semantic-UI#2836
=> Revert "Fix callback return from build task"

src/definitions/collections/menu.less
=> Add colored items on inverted menu.

README.md
#2924 Remove old info for Android
=> Remove old info

examples/responsive.html
=> Typo in HTML

src/definitions/elements/input.less
fix #2871
Example: https://github.com/Semantic-Org/Semantic-UI-Docs/pull/112
=> [Input] Support labels attached on both sides

src/themes/default/elements/icon.overrides
=> Remove duplicate icon aliases

src/definitions/behaviors/form.js
easy to access form data when using ajax submit in onSuccess
=> add form data as onSuccess callback param

src/definitions/behaviors/form.js
fix #2954 
Related commit 688c645 ... keeps returning false :)
=> [form] Get value of checkbox if its have

src/definitions/behaviors/form.js
fixes annoying issue :  https://github.com/Semantic-Org/Semantic-UI/issues/1172
=> Fix Add Errors Should Display Immediately #1172

src/definitions/modules/search.js
Fixes https://github.com/Semantic-Org/Semantic-UI/issues/3106
=> Call onSearchQuery whether or not results are cached

src/definitions/behaviors/form.js
=> [form] Fix integer validation

src/themes/default/elements/flag.overrides
=> [Flag] Adding Scotland and Wales

README.md
Fixed a few punctuation errors and edited a sentence to make it flow better.
=> Fixed punctuation and flow

src/definitions/modules/dropdown.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js
supported browsers reference: http://caniuse.com/#search=let
=> let is not supported on Safari

src/definitions/collections/form.less
=> [ref #4004] added inline fields to inverted form styling

RELEASE-NOTES.md
As of #3984, FA is now 4.6.3, not 4.5.0.
=> Update Font Awesome item in release notes

src/definitions/collections/menu.less
Fixed issue #4150.
Fixed the issue where the vertical menu item dropdown does not open upward properly.
=> [Dropdown] Fix issue #4150

src/definitions/elements/button.less
Example
```
<div class="ui vertical buttons">
<button class="ui button">Button</button>
</div>
```
[fiddle](http://jsfiddle.net/adcf0Ln5/2/)
Top of the button was not rounded
=> Sets border-radius when vertical buttons have a single child button

src/definitions/elements/icon.less
issue #4398 (Working screenshot below, hovering on the right)
=> Added hover styling to icon group

CONTRIBUTING.md, README.md
#4917 should be closed after merging.
=> Switched Project Talk to official forums in *md files

src/definitions/views/card.less
=> Fixed an issue with child `.card` elements inheriting their parents’ rules

README.md
https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history
Current stable is 15 :)
=> Update Edge supported versions

src/definitions/collections/table.less, src/themes/default/collections/table.variables
=> [Table] #5227 Added missing rules for sortable/inverted headers

src/themes/bookish/elements/header.overrides, src/themes/chubby/elements/button.overrides, src/themes/chubby/elements/header.overrides, src/themes/instagram/views/card.overrides, src/themes/rtl/globals/site.overrides
This resolves issue with mixed transports in production and makes these imports consistent with others.
=> Updated font imports to use HTTPS

src/theme.config.example, src/theme.less
Reverts Semantic-Org/Semantic-UI#5543
=> Revert "[Build Tools] Default theme folder can be configured"

README.md
I was looking for the link for way too long...
=> Add link to webpage at top of README

src/themes/default/globals/site.variables
Updated the YouTube colour to the new red.
https://www.youtube.com/intl/en-GB/yt/about/brand-resources/
=> Updated YouTube colour

src/definitions/globals/site.less, src/themes/default/globals/site.variables
See #5728 for issue details.
***
The [contributing docs say](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md#creating-pull-requests):
> All pull requests should be merged into the `next` branch.
But if I set that as the PR target it appears `next` is 13 commits behind master, so it wants to include those commits too. Is that instruction out of date maybe?
=> Fix horizontal scrollbar height, closes #5728

src/themes/default/modules/checkbox.variables
=> [Checkbox] Added `box-shadow` to the checkbox component’s `.toggle` variation

src/definitions/modules/dropdown.js
Reverts Semantic-Org/Semantic-UI#3432
=> Revert "[Dropdown] Allow ignoring of case when getting an item"

RELEASE-NOTES.md, src/definitions/modules/dimmer.js, src/definitions/modules/dimmer.less, src/definitions/modules/modal.js, src/definitions/modules/modal.less, src/themes/default/modules/dimmer.variables, src/themes/default/modules/modal.variables
* Adds flexbox dimmers
* Adds `centered` modal setting
* Adds `alignment` variatoins for dimmers
=> Centered modal

.github/ISSUE_TEMPLATE.md
Created an issue template as discussed https://github.com/Semantic-Org/Semantic-UI/issues/6109#issuecomment-366872453
Feel free to make changes 😄
=> Created issue template

src/definitions/modules/dropdown.js
`text` argument missing for select action
=> Fix for #4183

src/definitions/modules/search.less
#6158
Allow the disabled state for the search component.
=> [Search] add disabled style

.github/stale.yml, src/themes/default/elements/icon.overrides
[Icon] Wechat icon doesn't display
#6429
Add wechat to 'brand-icons' overrides
=> Fix #6429: [Icon] Wechat icon doesn't display

src/definitions/modules/modal.js
=> [Modal] Tears down mutation observer on modal destruction

src/definitions/modules/dimmer.js
=> Fix typo in dimmer.js

README.md
The first link to Gitter isn't a link...
(I'm partially filing this to see if this project is still alive.)
=> [Docs] Fix first link to gitter.im

RELEASE-NOTES.md
I really enjoyed using this project, nice work! Caught a couple of typos in the RELEASE-NOTES.mdthough 😛,
✖ Multiple features in one PR
✖ New Components Unless Previously Discussed with Maintainers (Consider creating separate repo, I'll link out to you)
✔ Add comments to complex/confusing code in "code" view of PR
✔ BUGS → This form is required:
✔ Enhancements → Only specific enhancements with detailed descriptions.
Use the format: [Component] Adds Support for Thing
For example: [Build Tools] Adds Source Map Support
Or: [Button] Fixes Inheritance for Red Basic Active State
#222 #333 #444
[Show before with this fiddle]
https://jsfiddle.net/ca0rovs3/
[Consider showing "fixed" case with your fiddle]()
You can link to your JS using https://rawgit.com/
=> Update RELEASE-NOTES.md, fix typos
